apiVersion: v2
name: nginx-template-chart
description: nginx Helm chart for Kubernetes
home: xxx
type: application
sources:
  - xxx
version: 1.0.0
appVersion: 1.0.0
keywords:
- nginx
maintainers:
- name: mingsha
  email: mingsha@example.com
