# 1、基础镜像
FROM mingsha.site:5555/base/dragonwell:jdk17-alpine-3.21

ENV TZ=Asia/Shanghai

# 2、在构建镜像时，指定镜像的工作目录。之后的命令都是基于此工作目录，不存在则自动创建。
WORKDIR /app/

# 3、复制制品内容到目标目录
COPY ./target/app ./

# 4、容器启动后执行命令
CMD ["sh","/app/bin/startup.sh"]
