# 1、基础镜像
FROM mingsha/jdk:dragonwell-17-alpine-3.22

# 2、镜像作者
LABEL maintainer="developer chenlong220192@gmail.com"

# 3、ENV
ENV TZ=Asia/Shanghai

# 4、在构建镜像时，指定镜像的工作目录。之后的命令都是基于此工作目录，不存在则自动创建。
WORKDIR /app/

# 5、复制制品内容到目标目录
COPY ./target/app ./

# 6、容器启动后执行命令
CMD ["sh","/app/bin/startup.sh"]
