management:
  endpoints:
    web:
      exposure:
        include: "*"            # 监控所有端点，其中health和status是必须监控的。
  endpoint:
    health:
      show-details: ALWAYS

# info信息会显示到SBA的server端，这里取的是maven中的数据
info:
  name: ${spring.application.name}
